const app=document.getElementById('app');
let editor, fallback;
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const api=u=>fetch(u).then(r=>r.json());
const path=()=>decodeURIComponent(location.pathname).replace(/^\/+|\/+$/g,'');
const go=u=>{history.pushState({},'',u);render()};
function home(){app.innerHTML=`<main class="search-home"><section class="home-hero"><p class="kicker">PHASER SYNTAX ENGINE</p><h1><span>Phaser</span> 문법 검색</h1><p>문서 이름 우선, 문서 내용 후순위로 검색합니다.</p></section><section class="search-panel"><form id="f" class="search-bar"><span class="search-icon">⌕</span><input id="q" placeholder="sprite, config, camera..."/><button class="primary-button">검색</button></form></section><section id="resultsArea" class="results-area"></section></main>`;document.getElementById('f').onsubmit=e=>{e.preventDefault();search(document.getElementById('q').value)}}
async function search(q=''){const data=await api('/api/search?q='+encodeURIComponent(q));const list=data.results||[];document.getElementById('resultsArea').innerHTML=list.map(r=>`<a class="result-card" href="/${encodeURIComponent(r.slug)}" data-nav><div class="result-meta"><span class="badge">${esc(r.category)}</span></div><h3>${esc(r.title)}</h3><p>${esc(r.snippet||r.summary)}</p></a>`).join('')||'<div class="empty-state">결과 없음</div>'}
function nav(){return`<header class="top-nav"><div class="top-nav-inner"><a class="brand-link" href="/" data-nav><span class="brand-orb">P</span><span>Phaser Syntax Search</span></a><a class="ghost-button" href="/" data-nav>메인으로 돌아가기</a></div></header>`}
async function doc(slug){const data=await api('/api/docs?slug='+encodeURIComponent(slug));const d=data.doc;if(!d){home();return}app.innerHTML=nav()+`<main class="doc-shell"><article class="doc-main"><section class="doc-hero"><p class="kicker">${esc(d.category)}</p><h1>${esc(d.title)}</h1><p>${esc(d.summary)}</p></section><section class="doc-body">${(d.sections||[]).map(s=>`<section class="doc-section"><h2>${esc(s.heading)}</h2>${(s.paragraphs||[]).map(p=>`<p>${esc(p)}</p>`).join('')}${s.code?`<pre class="code-block"><code>${esc(s.code)}</code></pre>`:''}${s.list?`<ul>${s.list.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}</section>`).join('')}<section class="code-lab"><div class="code-lab-head"><div><h2>작은 Monaco Editor</h2><p>문서의 일부처럼 작은 코드 실행 영역입니다.</p></div></div><div id="ed" class="editor-frame"><textarea class="editor-fallback">${esc(d.code||'console.log("Phaser")')}</textarea></div><div class="run-row"><button id="run" class="primary-button">Node.js로 실행</button><span id="st" class="status-text">대기 중</span></div><pre id="out" class="output-pre">결과가 여기에 표시됩니다.</pre></section></section></article><aside class="related-sidebar"><div class="related-card"><h2>연관된 문서</h2><div class="related-list">${(data.related||[]).map(r=>`<a class="related-link" href="/${encodeURIComponent(r.slug)}" data-nav><strong>${esc(r.title)}</strong><small>${esc(r.summary)}</small></a>`).join('')}</div></div></aside></main>`;fallback=document.querySelector('textarea');loadEditor(d.code||fallback.value);document.getElementById('run').onclick=run}
function loadEditor(code){if(!window.require)return;window.require.config({paths:{vs:'https://cdn.jsdelivr.net/npm/monaco-editor@0.52.2/min/vs'}});window.require(['vs/editor/editor.main'],()=>{const el=document.getElementById('ed');fallback.remove();editor=monaco.editor.create(el,{value:code,language:'javascript',theme:'vs-dark',fontSize:12,minimap:{enabled:false},automaticLayout:true})})}
async function run(){const code=editor?editor.getValue():fallback.value;const r=await fetch('/api/'+'run-node',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code,stdin:'',files:{}})});const t=await r.text();try{document.getElementById('out').textContent=JSON.parse(t).payload||t}catch{document.getElementById('out').textContent=t}document.getElementById('st').textContent='완료'}
document.addEventListener('click',e=>{const a=e.target.closest('[data-nav]');if(a){e.preventDefault();go(a.getAttribute('href'))}});window.onpopstate=render;function render(){const s=path();s?doc(s):home()}render();
